/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResumeDottxtRouteImport } from './routes/resume[.]txt'
import { Route as ResumeDotjsonRouteImport } from './routes/resume[.]json'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WritingSlugRouteImport } from './routes/writing.$slug'
import { Route as CaseStudiesSlugRouteImport } from './routes/case-studies.$slug'
import { Route as ApiSpotifyRouteImport } from './routes/api.spotify'
import { Route as ApiGithubActivityRouteImport } from './routes/api.github-activity'
import { Route as ApiCodexActivityRouteImport } from './routes/api.codex-activity'
import { Route as ApiInternalCodexSyncRouteImport } from './routes/api.internal.codex-sync'

const ResumeDottxtRoute = ResumeDottxtRouteImport.update({
  id: '/resume.txt',
  path: '/resume.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeDotjsonRoute = ResumeDotjsonRouteImport.update({
  id: '/resume.json',
  path: '/resume.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingSlugRoute = WritingSlugRouteImport.update({
  id: '/writing/$slug',
  path: '/writing/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesSlugRoute = CaseStudiesSlugRouteImport.update({
  id: '/case-studies/$slug',
  path: '/case-studies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpotifyRoute = ApiSpotifyRouteImport.update({
  id: '/api/spotify',
  path: '/api/spotify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubActivityRoute = ApiGithubActivityRouteImport.update({
  id: '/api/github-activity',
  path: '/api/github-activity',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCodexActivityRoute = ApiCodexActivityRouteImport.update({
  id: '/api/codex-activity',
  path: '/api/codex-activity',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalCodexSyncRoute = ApiInternalCodexSyncRouteImport.update({
  id: '/api/internal/codex-sync',
  path: '/api/internal/codex-sync',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/playground': typeof PlaygroundRoute
  '/resume': typeof ResumeRoute
  '/resume.json': typeof ResumeDotjsonRoute
  '/resume.txt': typeof ResumeDottxtRoute
  '/api/codex-activity': typeof ApiCodexActivityRoute
  '/api/github-activity': typeof ApiGithubActivityRoute
  '/api/spotify': typeof ApiSpotifyRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/api/internal/codex-sync': typeof ApiInternalCodexSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/playground': typeof PlaygroundRoute
  '/resume': typeof ResumeRoute
  '/resume.json': typeof ResumeDotjsonRoute
  '/resume.txt': typeof ResumeDottxtRoute
  '/api/codex-activity': typeof ApiCodexActivityRoute
  '/api/github-activity': typeof ApiGithubActivityRoute
  '/api/spotify': typeof ApiSpotifyRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/api/internal/codex-sync': typeof ApiInternalCodexSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/playground': typeof PlaygroundRoute
  '/resume': typeof ResumeRoute
  '/resume.json': typeof ResumeDotjsonRoute
  '/resume.txt': typeof ResumeDottxtRoute
  '/api/codex-activity': typeof ApiCodexActivityRoute
  '/api/github-activity': typeof ApiGithubActivityRoute
  '/api/spotify': typeof ApiSpotifyRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/api/internal/codex-sync': typeof ApiInternalCodexSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/playground'
    | '/resume'
    | '/resume.json'
    | '/resume.txt'
    | '/api/codex-activity'
    | '/api/github-activity'
    | '/api/spotify'
    | '/case-studies/$slug'
    | '/writing/$slug'
    | '/api/internal/codex-sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/playground'
    | '/resume'
    | '/resume.json'
    | '/resume.txt'
    | '/api/codex-activity'
    | '/api/github-activity'
    | '/api/spotify'
    | '/case-studies/$slug'
    | '/writing/$slug'
    | '/api/internal/codex-sync'
  id:
    | '__root__'
    | '/'
    | '/playground'
    | '/resume'
    | '/resume.json'
    | '/resume.txt'
    | '/api/codex-activity'
    | '/api/github-activity'
    | '/api/spotify'
    | '/case-studies/$slug'
    | '/writing/$slug'
    | '/api/internal/codex-sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlaygroundRoute: typeof PlaygroundRoute
  ResumeRoute: typeof ResumeRoute
  ResumeDotjsonRoute: typeof ResumeDotjsonRoute
  ResumeDottxtRoute: typeof ResumeDottxtRoute
  ApiCodexActivityRoute: typeof ApiCodexActivityRoute
  ApiGithubActivityRoute: typeof ApiGithubActivityRoute
  ApiSpotifyRoute: typeof ApiSpotifyRoute
  CaseStudiesSlugRoute: typeof CaseStudiesSlugRoute
  WritingSlugRoute: typeof WritingSlugRoute
  ApiInternalCodexSyncRoute: typeof ApiInternalCodexSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resume.txt': {
      id: '/resume.txt'
      path: '/resume.txt'
      fullPath: '/resume.txt'
      preLoaderRoute: typeof ResumeDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume.json': {
      id: '/resume.json'
      path: '/resume.json'
      fullPath: '/resume.json'
      preLoaderRoute: typeof ResumeDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing/$slug': {
      id: '/writing/$slug'
      path: '/writing/$slug'
      fullPath: '/writing/$slug'
      preLoaderRoute: typeof WritingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/$slug': {
      id: '/case-studies/$slug'
      path: '/case-studies/$slug'
      fullPath: '/case-studies/$slug'
      preLoaderRoute: typeof CaseStudiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/spotify': {
      id: '/api/spotify'
      path: '/api/spotify'
      fullPath: '/api/spotify'
      preLoaderRoute: typeof ApiSpotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github-activity': {
      id: '/api/github-activity'
      path: '/api/github-activity'
      fullPath: '/api/github-activity'
      preLoaderRoute: typeof ApiGithubActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/codex-activity': {
      id: '/api/codex-activity'
      path: '/api/codex-activity'
      fullPath: '/api/codex-activity'
      preLoaderRoute: typeof ApiCodexActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/codex-sync': {
      id: '/api/internal/codex-sync'
      path: '/api/internal/codex-sync'
      fullPath: '/api/internal/codex-sync'
      preLoaderRoute: typeof ApiInternalCodexSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlaygroundRoute: PlaygroundRoute,
  ResumeRoute: ResumeRoute,
  ResumeDotjsonRoute: ResumeDotjsonRoute,
  ResumeDottxtRoute: ResumeDottxtRoute,
  ApiCodexActivityRoute: ApiCodexActivityRoute,
  ApiGithubActivityRoute: ApiGithubActivityRoute,
  ApiSpotifyRoute: ApiSpotifyRoute,
  CaseStudiesSlugRoute: CaseStudiesSlugRoute,
  WritingSlugRoute: WritingSlugRoute,
  ApiInternalCodexSyncRoute: ApiInternalCodexSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
